name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Build app
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Run build
      run: yarn build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        CLEAN: true
